### ISSUE TITLE
Set time

### ISSUE THREAD

**Issue by Marabun** [Marabun/Spy_BTC_price#101]
При разовом событии нужно писать оставшееся время до события(в screenbotton). Посмотри как это сделано в Skeddy.

![через 5 часов.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b44ec46ec350000137a4caf/125516c66e82c728ace21e0d4659732af63363195a596803f11d41739996969299da13f932c9a138ad4d71040c1b5ca6535d0d40f8acdd2cafe569708d0d0cedd16c0a77c33e18afbd9003ad43eb7edf10d8eff6df0ed2e22f24ee818e4a3d1b041880f95532a7994cda15.jpg)

**Comment by Alehow** [comment]
а если вместо этого просто говорить КОГДА это произойдет?

**Comment by Marabun** [comment]
Можно и так.

**Comment by Alehow** [comment]
хорошо что ты согласился, а то я уже почти закончил это делать таким образом))

**Comment by Marabun** [comment]
Так, в целом нет проблем, суть ведь в том, что бы пользователь понимал когда этот сигнал сработает и не был дезориентирован.
