### ISSUE TITLE
Быстрые настройки

### ISSUE THREAD

**Issue by Alehow** [Marabun/Spy_BTC_price#125]
Изменения не вступают в силу (выделено на рисунке)

**Comment by Alehow** [comment]
![Снимок.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a78339ad9a61700135eaf3e/125516c66e82c728ace21e0d4658552afe325b19535961f37e1fbcd6395428792c07b7692ac7b62aeb167e0558561df9415f0e43fcf9887ea5b33f79895919f1c32f0e2a92624cf5f2d75dad0ba821824584b3bf8c4cc7eb3c21ef8287472c53.JPG)

**Comment by Marabun** [comment]
Ого, как я такое пропустил!

**Comment by Alehow** [comment]
Можешь сам проверить. Ставишь процент, потом меняешь валюту или биржу. Потом выходишь в главное меню. Заходишь в алерты, жмешь изменить процент, и видешь что изменения в силу не вступили
