### ISSUE TITLE
Биткойн калькулятор_2

### ISSUE THREAD

**Issue by Marabun** [Marabun/Spy_BTC_price#13]
Как я вижу работу калькулятора.
Диалог бота предполагающего ввести сумму и валютную пару, где первой указана валюта относящаяся к числу, а второй рассчитываемая.
Пользователь вводит число и направление расчета(пару) - "1 USD/BTC", результат - "1 USD = 0.0001563 BTC", или "0.1 BTC/USD", результат 0.1 BTC = 637.5 USD". USD,BTC прочие валютные обозначения должны иметь алиасы, т.е если юзер напишет 1 Доллар(бакс,USD, dollar)/биткоин(биткойн,биток,бтц,бтк,Bitcoin,BTC) бот должен понять. Это же касается разделителя пары /,=,-,запятая, точка.

**Comment by Alehow** [comment]
![photo_2018-07-23_10-20-43.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a78339ad9a61700135eaf3e/125516c66e82c728ace21e0d46f89c95378dbcfbdfb8e70ef40abdc67a7976236456f36624d6a164fd52690e050a1de853524d41aefd8d7ef2b13523df5c0cbcd66d5f75933e14afb1811aad1da862da11d1e9e1d30695aa2f2ff58a88453f1b061a8afc5d31a59049c05fe406.jpg)

**Comment by Alehow** [comment]
Вот как вижу это я: у нас будет меню как на картинкие. С помощью кнопок пользоваель выбирает направление обмена и отправляет нам чило. Например с помощью кнопок он выбирает BTC слева и USD справа, затем он отправляет нам число 0,1, вот выдаёт нам " 0.1 BTC = 755,3 USD". Как тебе такой подход?

**Comment by Marabun** [comment]
Давай попробуем. А что с предложенным подходом, что увидел не так?

**Comment by Alehow** [comment]
Предложеный тобой подход может показаться сильно сложным для некоторых юзеров, кроме того количество допускаемых ошибок пользователем будет в разы больше если он будет сам в ручную всё вводить. Мне кажется что если где-то можно добавить кнопку - то надо добавлять
