### ISSUE TITLE
Диагоги (about)

### ISSUE THREAD

**Issue by Marabun** [Marabun/Spy_BTC_price#140]
Нажмите "Прочитать" что бы ознакомиться с инструкцией по использованию бота.
Или задайте вопрос в нашей группе кликнув кнопку "Написать".
[Прочитать] [Написать] - поменять местами.

**Comment by Alehow** [comment]
Возможно нам есть смысл оставить кнопку "написать" первой, так, я надеюсь, больше людей захочет на неё нажать. Или это бред?

**Comment by Marabun** [comment]
Ок, оставляй.
