### ISSUE TITLE
Диагоги (валюта)

### ISSUE THREAD

**Issue by Marabun** [Marabun/Spy_BTC_price#142]
* Цена валюты со звездочкой конвертируется из доллара по текущему курсу. Прямой курс невозможен из-за отсутствия валюты на выбранной бирже.

![SmartSelect_20180911-022114_Plus.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b44ec46ec350000137a4caf/125516c66e82c728ace21e0d46db999b3196b0ac83ecbc579b0fa0c571167e227849f37922d4b27c807277141c4d52be011a001ea9aacd39aca439228e585eb9d6640c21c63a40abb8821eea02bf23824c80a4a0980e91b6697abad2c51a7c0c0f0a88f75734a59a4dce5af448e1445ca316242e.jpg)

**Comment by Alehow** [comment]
"валюты зависят от выбраой биржи" убирать?

**Comment by Marabun** [comment]
Да. Этот смысл в словах "отсутствия валюты на выбранной бирже."
