### ISSUE TITLE
Взаимодействие(реакция)  бота

### ISSUE THREAD

**Issue by Marabun** [Marabun/Spy_BTC_price#16]
В "Главном меню", если пользователь отправляет любое сообщение боту показывать диалог - "Похоже это не работает :) Попробуйте предлагаемые кнопки."

**Comment by Alehow** [comment]
Почему только в главном меню? Я думаю можно везде так

**Comment by Marabun** [comment]
Согласен. Этот диалог нужен в состояниях когда бот не ожидает ввода с андроид клавиатуры.
