### ISSUE TITLE
Баг (set time)

### ISSUE THREAD

**Issue by Marabun** [Marabun/Spy_BTC_price#167]
![photo_2018-09-21_21-06-16.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b44ec46ec350000137a4caf/125516c66e82c728ace21e0d46f89c95378dbcfbdfb8e70ef404bdc6787975226454f56621d3a164fd52690e050a1de853524d41aefd8d7ef2b13523df5c0cbcd66d5f75933e14afb1811aad1da862da11d1e9e1d30695aa2f2ff58a86453f1b061f8cfa5835a29e43c058e406.jpg)

**Comment by Alehow** [comment]
"раз в неделю" он тоже не понимает

**Comment by Marabun** [comment]
Обучай.
