### ISSUE TITLE
Диагоги (детали)

### ISSUE THREAD

**Issue by Marabun** [Marabun/Spy_BTC_price#169]
Два вопроса:
1.Почему знак минус при 0.0%
2.Почему это ряд смещен назад, такое смещение я замечаю в любом ряду при значении именно "0.0%".

![Screenshot_20180922-213432_Plus.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b44ec46ec350000137a4caf/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc791f75216456f27824d6b1178f4e6e124d435cec03070511afbd9b21b4b36e748e095fead83e0a74c16c16acb8834abc04b929884a97aaaec81d9ebc6278bec1da0d2c14171981f55c30a39e4dcc59f34de34e57a4017b.jpg)

**Comment by Alehow** [comment]
когда 0,0 без минуса тоже смещается?

**Comment by Marabun** [comment]
Не замечал.

**Comment by Alehow** [comment]
в общем ситуация такая: минус перед 0.0 появляется из-за того что мы округляем маленькое отрицательное число (на пример -0,0001) Я это исправлю

**Comment by Marabun** [comment]
Отлично.
