### ISSUE TITLE
Данные пользователей

### ISSUE THREAD

**Issue by Alehow** [Marabun/Spy_BTC_price#17]
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#general-code-snippets

Изучить и применить пункт "Store ConversationHandler States"

**Comment by Alehow** [comment]
В теории, это позволит перезапускать бота столько, сколько нам нужно, и при этом не беспокоть пользователей.

**Comment by Marabun** [comment]
Круто, пробуем.
