### ISSUE TITLE
Диагоги (цена)

### ISSUE THREAD

**Issue by Marabun** [Marabun/Spy_BTC_price#209]
Добавить показ биржи
![20181029_120341.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b44ec46ec350000137a4caf/125516c66e82c728ace21e0d46bac4cb7bd3d3fbd6d6ee11f40ea4c56b0a65633b0ba92e7391a172fd1779555b0a1aab480b0a44fba88e2ba6b769738f5f02eed47f4366846c4ff8e7df46f554f832815d84b1b68b49c4e83525e08e8b4e3a18060ac4.jpg)

**Comment by Alehow** [comment]
биржа показывается в деталях. Может оставим как есть? Типа показываем самую важную инфу сразу, а биржи и т.д. в деталях

**Comment by Marabun** [comment]
Совсем не удобно, не хватает информации откуда цена. Я вообще всегда открываю детали и начинаю подумывать че мы эту инфу прячем.

**Comment by Alehow** [comment]
а ты что,биржи часто меняешь? по идее мы в настройках один раз выбираем нужные нам валюту и биржу и  всё, забываем. 

Раз тебе не удобно - сделаю
