### ISSUE TITLE
Статистика

### ISSUE THREAD

**Issue by Alehow** [Marabun/Spy_BTC_price#214]
Показывать общую статистику

**Comment by Marabun** [comment]
![SmartSelect_20181102-134952_Samsung Notes.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b44ec46ec350000137a4caf/125516c66e82c728ace21e0d46db999b3196b0ac83ecbc579b0fa0c5711776237b49f27824dcb67a80717a0c1c1a10fb51260000a9ba9b37b4f67e2fd00958a9c3674d71943915f9ec8516ec54ba27da4885b6bddf4fc5eb3426e299935d7c4f5b4cd6a2047ff5db59c24af74ceb4c50a0123766ef72367445941c6761.jpg)
