### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by Marabun** [Marabun/Spy_BTC_price#219]
Нужна кнопка, в самом низу, "<--- К статистике"
![Screenshot_20181104-011343_Plus.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b44ec46ec350000137a4caf/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc781777276454f27a23d1b0178f4e6e124d435cec03070511afbd9b21b4b36e748e095fead83e0a74c16c16acb8834abc04b929884a97aaaec81d9ebc6278bec1da0d2c14171a8bf55c30a49849c05efe4de74c5da6017b.jpg)

**Comment by Alehow** [comment]
куда она должна вести? к последней дате в которой я был перед календарём?

**Comment by Marabun** [comment]
Да
