### ISSUE TITLE
Игра, кнопки в канале.

### ISSUE THREAD

**Issue by Marabun** [Marabun/Spy_BTC_price#236]
Как думаешь, есть смысл ниже кнопок прогноза, сделать кнопку "К боту"? А над диалогом о раунде кнопку "Правила" по клику краткие описание и кнопка "Свернуть"

**Comment by Alehow** [comment]
я не до конца понял смысл кнопки правила. как она будет размещаться? над диалогом по моему будет не красиво. Сворачивать/разворачивать правила тоже не вариант они будут разворачиваться и сворачиваться одновременно для всех. Луче сделать ссылку не телегра.пх
