### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by Marabun** [Marabun/Spy_BTC_price#262]
Я вызвал справку будучи в Главном меню, просто через /guide. После перехода оказался не в начале справки, а в описании Калькулятора.... Заметил, что если перейти в другие разделы, то там гайды вызываются с правильного места, но если вернуться в Главное и вызвать гайд, то будет показано с места последнего посещенного раздела.

**Comment by Alehow** [comment]
Гайд по идее должен вызываться именно для  разделов? Есть стандартные команды  /start и /help которые есть практически у всех ботов, вот у нас команда хелп в любой из директорий отправит в начало гайда. Сделать так, что бы гайд отправлял в начало,когда его вызывают из главного меню, не проблема

**Comment by Marabun** [comment]
Ок. Делай.
