### ISSUE TITLE
Добавить название биржи

### ISSUE THREAD

**Issue by Marabun** [Marabun/Spy_BTC_price#270]
![Screenshot_20190108-181743_Plus.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b44ec46ec350000137a4caf/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cd7917772b6455fb7a27d1b0178f4e6e124d435cec03070511afbd9b21b4b36e748e095fead83e0a74c16c16acb8834abc04b929884a97aaaec81d9ebc6278bec1da0d2c14171a89f55c30a49f42ce5cf54ee04d5ca1017b.jpg)

**Comment by Alehow** [comment]
Так ведь уже давно сделал... Ты это точно в тест1 смотрел? или это в Криптусе?(туда я еще не добовлял)

**Comment by Marabun** [comment]
Ок
