### ISSUE TITLE
Название кнопки

### ISSUE THREAD

**Issue by Marabun** [Marabun/Spy_BTC_price#43]
Alarms - это не множественное число, а Сигнализация.
А вот Alarm, хотя и может переводиться Сигнализация, но обычно используется как Будильник, тревога... 
В общем нет смысла писать "s" в конце.

**Comment by Alehow** [comment]
может тогда  Notifications?

**Comment by Marabun** [comment]
Alerts.
Если не нравиться пиши твой вариант, мне просто кажется Notifications длинное название, сейчас это не проблема. Но если предположить что мы сделаем три кнопки в ряду, то нужно смотреть как это будет вмещаться. 
Третья кнопка возможна в будущем, если добавить Chat(хочу чтоб она была на виду, хотя будет лишь перекидывать в группу), Blockchain(это пока идея), а также добавление альтов может потянуть необходимость добавить Altcoins, или что-то подобное.
Итог, может понадобиться доп. кнопки в первых двух рядах(как минимум).

**Comment by Alehow** [comment]
Alerts нарвится
