### ISSUE TITLE
Screenbutton

### ISSUE THREAD

**Issue by Marabun** [Marabun/Spy_BTC_price#50]
Надо ли? 
Добавить "стоп" под алертами.

**Comment by Alehow** [comment]
Тут по подробнее, не совсем тебя понял. У нас же уже есть стоп под процентом, под ценой у нас кнопки со всеми алертами, какой надо удалить - нажимай и удаляй

**Comment by Marabun** [comment]
Я о алертах которые мы получаем.
![Screenshot_20180730-161030__01.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b44ec46ec350000137a4caf/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc791174236455f57a20d6b31780122a43434d0eee1e020a17b8eb8339a3e43874df080ce482385f73973a11acb9d71cba02b3238e5d99a4fedb1294b7607caddecd5d340c041f83fe5836a2904ece5af048e04556b65e.jpg)

Хотя сейчас смотрю, и кажется будет не красиво, если будет столб уведомлений и после каждого "Стоп". Я это представлял как возможность постановки без необходимости ходить в "Оповещения", типа все тут же под рукой, разумеется функция остановки в Оповещении тоже остается. Но возможно надо попробовать.
