### ISSUE TITLE
Диалоги (Детали)

### ISSUE THREAD

**Issue by Marabun** [Marabun/Spy_BTC_price#55]
Вчера столкнулся со следующим вопросом: если курс с EXMO, то вся остальная инфа тоже? Что вызвало вопрос? Во-первых расположение надписи Rate from EXMO под курсом, если не учитывать разделители, то это как бы относит надпись к всему что ниже в том числе, но это субъективное восприятие.  Вероятно нужно при клике на "Детали" показывать детали более однозначно, и добавить "From Coinmarketcap"

Кстати, здесь не видно все форматирование, но у меня было видиние более "чистого" визуала:
![Screenshot_20180730-145425__01.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b44ec46ec350000137a4caf/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc791174236455f77e24d7b61780122a43434d0eee1e020a17b8eb8339a3e43874df080ce482385f73973a11acb9d71cba02b3238e5d99a4fedb1294b7607caddecd5d340c041183fe5836a2904ec95ff749e34a54b65e.jpg)

Rate from EXMO: и From Coinmarketcap:
Дефисы по центру, и только как разделение курса и данных с КМК.
Удалить двоеточие у строк в деталях КМК, создают визуальный шум.

**Comment by Alehow** [comment]
Тут вся инфа с КМК, можно добавить подсказку об этом сразу, а можно просто указать это где-то в гайде или хелпе. Но мне кажется будет лучше напомитать то что инфа с КМК каждый раз

**Comment by Marabun** [comment]
Где-то в гайде, или хелпе не то, хотя там тоже можно в качестве описания, а вот здесь нужно сразу, тк это же "Детали". Причем мы же не делаем пространных описаний, просто и кратко для ориентации.
