### ISSUE TITLE
Правка диалогов

### ISSUE THREAD

**Issue by Marabun** [Marabun/Spy_BTC_price#85]
С одной M если по английски.

![Screenshot_20180810-082218__01.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b44ec46ec350000137a4caf/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc791e76236454fb7922d4bb1780122a43434d0eee1e020a17b8eb8339a3e43874df080ce482385f73973a11acb9d71cba02b3238e5d99a4fedb1294b7607caddecd5d340c071883fe5836a3914cc05ff64ae34a55b65e.jpg)

**Comment by Alehow** [comment]
исправленно в #71
