### ISSUE TITLE
Функционал

### ISSUE THREAD

**Issue by Marabun** [Marabun/Spy_BTC_price#89]
Добавить в меню текст о состоянии слежки: постоянно или разово.
В зависимости от статуса показывать скрин батон изменяющий состояние на противоположное.
Диалог:
Вы установили ...%
Оповещать постоянно,
*можно изменить на:*
[Разово]

![Снимок экрана 2018-08-14 в 13.36.48.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b44ec46ec350000137a4caf/125516c66e82c728ace21e0d4658552afe325b19535961f37e1d4179999c969399d413f6c055a37aef13234c5f5753ad4548bfc6ecf88a35a5b02274824e17ff912f002e936e55beb2901aed05be75df488ce5e98a4b91ef3d25e6de8c4a3d17061d9be34f77f1c71f9705af01b40f47ae01376aec77337f43961a762868602fafffcd1b.png)

**Comment by Alehow** [comment]
а зачем? у нас ведь теперь есть кнопка стоп под последним оповещением. Захочет один раз - нажмет стоп как только получит оповещение

**Comment by Marabun** [comment]
Ну, это как бы функционал в установке, здесь ты по сути осуществляешь настройку. И возможно тебе не хочется парится с кнопкой на "Главной", и ты вообще читаешь сообщение бота через уведомление даже не открывая телеграмм. Я лично часто читаю уведомления не открывая сам телеграмм, а ты нет?

**Comment by Alehow** [comment]
Нет, мне обязательно надо открыть :)

**Comment by Marabun** [comment]
Как видишь есть варианты использования, оно не с одним сценарием, поэтому нужно заложить возможности.
