### ISSUE TITLE
Названия custombutton

### ISSUE THREAD

**Issue by Marabun** [Marabun/Spy_BTC_price#9]
Названия кнопок в "Инструменты для слежки" - "Изменения процента", "Фиксированная цена".

**Comment by Alehow** [comment]
Изменение процента - не очень отображает суть функции. Может лучше "отслеживане цены"?

**Comment by Marabun** [comment]
Логика следующая, на первом шаге пользователь получает информацию с кнопки главного меню. Что он понимает? "инструменты для слежки" значит будут какие то функции отслеживания цены. Переходя в раздел он получает уточнение уже имеющейся информации, а именно:  изменения процента(это новая информация), и она отражает суть функции. Вместе имеем информацию о слежении и уточнение каким образом. Если ты не показывал Ане, попробуй провести эксперимент с ней, какой подход более понятен.

Почему я вообще на обратил внимание? "Следить за ценой", "Отслеживать цену", или "Добавить оповещение о цене" по моим ощущениям не раскрывают сути метода каким образом эту будет производиться. Если учесть что мы находимся в "Инструментах для слежки", то понятно что здесь будут функции отслеживания с оповещением(это же Телеграмм-платформа) , а вот что конкретно они делают? Поэтому "Изменения процента"(именно "изменения" т.к это множ. процесс, а не разовый) и "Фиксированная цена" показались больше дающие инфы о методе их работы.

**Comment by Alehow** [comment]
Может тогда лучше "изменения в процентах" или "изменения цены в процентах"?

**Comment by Marabun** [comment]
Изменения в процентах.
Ты с Аней провел эксперимент?

**Comment by Alehow** [comment]
Да, когда я ей дал поклацать бота она не могла понять чем отличается "следить за ценой" от "добавить оповещен е о цене"

**Comment by Marabun** [comment]
У нее были мысли по вариантам улучшения данного вопроса. Что приходило сразу в голову?

**Comment by Alehow** [comment]
Ей приходило в голову то что я  написал "отслеживание цены". И еще вопрос. кнопка "добавить оповещение", или как ты хочешь еёпоменять - "фиксированая цена". Аналог этой кнопки изображен на рисунке,  который я отправил в телеге. Так вот может стоит отталкиваться от этоо самого Alarm в названии?
