### ISSUE TITLE
Скрин батон

### ISSUE THREAD

**Issue by Marabun** [Marabun/Spy_BTC_price#95]
Дать возможность юзеру оценить правильность часового пояса. Под диалогом "Вы установили часовой пояс ..." кнопки "Верно" "Ошибка" и только после подтверждения показывать остальные диалоги.

![Screenshot_20180822-170242__01.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b44ec46ec350000137a4caf/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc791e75216455f47b22d1b11780122a43434d0eee1e020a17b8eb8339a3e43874df080ce482385f73973a11acb9d71cba02b3238e5d99a4fedb1294b7607caddecd5d340c071a83fe5836a4904fcf58f649e74856b65e.jpg)

**Comment by Alehow** [comment]
Это я так понимаю после отправки геолокации?
допустим пользователь нажал "ошибка",  какая должна быть реакция?

**Comment by Marabun** [comment]
Как вариант предложить:
Давайте искать решение. Если вы отправляли геолокацию и она неверно определилась, то возможно:
1 выключена передача геоданных, включите GPS
2  включен VPN/proxy,  отключите его. 
Если эти условия выполнены, отправьте мне одним сообщение название Вашего города и страны.

**Comment by Alehow** [comment]
Если GPS отключен то геолокацию ты никак не отправишь (разве что вручную, пальцем в карту тыкнуть) можешь проверить. VPN тоже не влияет. Если юзер скинет название города то это никак не поможет, ведь мы этот же самый город получаем из геолокации

**Comment by Marabun** [comment]
Получается правильно определения будет практически 100%

**Comment by Alehow** [comment]
да

**Comment by Marabun** [comment]
Тогда никаких заморочек. Единственное нужно написать в диалоге примечание прописью - _Изменить часовой пояс можно в Настроках выбрав пункт Время._

**Comment by Alehow** [comment]
ok
