### ISSUE TITLE
Диалоги (время)

### ISSUE THREAD

**Issue by Marabun** [Marabun/Spy_BTC_price#99]
Простите, не разобрал. Уточните время?

Если говорить - В какое время мне сказать вам цену?, то человек может подумать "Я же тебе только что сказал".

![Снимок экрана 2018-08-23 в 21.00.56.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b44ec46ec350000137a4caf/125516c66e82c728ace21e0d4658552afe325b19535961f37e1d4179999c969399d413f6c055a37aef13234c5f5753ae4248bfc6ecfb8835a6b622758c4e17ff912f002e936e55beb2901aed05be75df488ce5e98a4b91ef3d25e6de8c4a3d17061d9be34f77f1c71f9705af01b40f47ae01376bec77337f42941a72286f6721a9facd1b.png)

**Comment by Alehow** [comment]
Если сказать "простите, не разобрал" юзер может решить что его вообще не поняли.  я добавлю ему понимание " это время"

**Comment by Marabun** [comment]
Хорошо, добавляй. 
"Если сказать "простите, не разобрал" юзер может решить что его вообще не поняли", да, так это и нужно. Что он должен понять, если после ввода времени видит - В какое время мне сказать вам цену?

**Comment by Alehow** [comment]
Допустим юзер пишет "завтра в это время", Бот отвечает "простите, не разобрал", но ведь мы разобрали что надо сказать завтра, только время не поняли

**Comment by Marabun** [comment]
Мне нравится твой похдод )). Тогда будет отвечать - Я понял что завтра, но в какое время? Только в таком случае прийдется делать еще кучу работы.

**Comment by Marabun** [comment]
Объясни мне разницу в понимании юзера, если он видит 1. В какое время мне сказать вам цену? или 2. ... Уточните время?

**Comment by Alehow** [comment]
Тут разницы нет, но прчем тут это? мы обсуждаем фразу "я не разобрал"
